#!/usr/bin/env node
const chalk = require('chalk')
const child_process = require('child_process')
const { version } = require("./package.json")
const fs = require('fs');
const { LogType, log } = require("./src/logger.js")

if (!fs.existsSync("./config.json")) {
	log(LogType.Error, `Config does not exist! Make a copy of the file "config.template.json", rename it to "config.json", and edit the values inside the config.`)
	process.exit(1)
}

log(LogType.Debug, "Debug Logging Enabled!")

const { discord_bot, token_signature, allow2016AndEarly2017, clearImageCacheOnLaunch } = require("./config.json")
const { webhookMessage } = require("./src/webhook.js")

if (token_signature === "LunarRec_ReplaceMeWithSomethingElsePlz") {
	log(LogType.Warn, "⚠️SECURITY RISK DETECTED - CHANGE YOUR JWT TOKEN SIGNATURE⚠️")
	log(LogType.Warn, "Your \"token_signature\" in your config is still set to the default value!")
	log(LogType.Warn, "This means anyone can create JWT tokens and log into any account!")
	log(LogType.Warn, "Please change this variable to something long and unique.")
} else if (token_signature.length < 10) {
	log(LogType.Warn, "⚠️SECURITY RISK DETECTED - CHANGE YOUR JWT TOKEN SIGNATURE⚠️")
	log(LogType.Warn, "Your \"token_signature\" in your config is less than 10 characters.")
	log(LogType.Warn, "This makes it easier for people to brute force your JWT password!")
	log(LogType.Warn, "Please change this variable to something long and unique.")
}

if (allow2016AndEarly2017) {
	log(LogType.Warn, "⚠️EARLY BUILD MODE ENABLED⚠️")
	log(LogType.Warn, "This server has \"allow2016AndEarly2017\" in the config set to true.")
	log(LogType.Warn, "Due to weak security, it is easy for anyone to generate auth tokens.")
	log(LogType.Warn, "Please disable old build mode if you aren't supporting 2016 and early 2017 builds.")
}

let colors = require('./colors.json')

try{process.commit = child_process.execSync('git rev-parse HEAD').toString().substring(0, 7)} catch(e) {process.commit = "[git not installed]"}

let versionStr = ` Version ${version} (commit ${process.commit})`

console.log(`${" ".repeat((versionStr.length-"lunarrec".length)/2)}${chalk.hex(colors.logo)("LunarRec")}\n${versionStr}\n${"=".repeat(versionStr.length+1)}`)

if (process.argv[2] == "reset"){
	return require('./util.js').resetServerData()
}

process.db = require('./database.js')

if (process.argv[2] == "admin"){
	return require("./src/admin.js").admin()
}

async function start() {
	if (!fs.existsSync("./.first_run")) {
		fs.writeFileSync("./.first_run", "# Dummy file generated by LunarRec.\n# Completed: " + new Date())
		console.log(`Hello there 👋! 
It looks like this is your first time running LunarRec.
Please check out the github repo for first time install steps.
Also note that LunarRec is still a heavy work in progress project.

To read this message again, Delete the file ".first_run" in the root directory.
`)}

	await process.db.users.sync()

	try {
		await process.db.users.update({ session: null }, { where: {} });
	} catch (error) {
		log(LogType.Error, "Failed to set user sessions to NULL.")
	}

	if (clearImageCacheOnLaunch) {
		require('./util.js').clearImages()
	}

	if (discord_bot.enabled) {
		log(LogType.Bot, "Discord Bot enabled!")
		require(`./src/bot/deploy.js`)
		require('./src/bot/index.js')
	}

	require('./src/server.js')
	webhookMessage(0, "")
}

process.on('SIGTERM', () => {
	console.log('SIGTERM received, shutting down gracefully...');
	process.exit(0);
});

process.on('SIGINT', () => {
	console.log('SIGINT received, shutting down gracefully...');
	process.exit(0);
});

start().catch(err => {
	console.error(err);
	process.exit(1);
});